export const paramsList = [{
  option: 'wait_timeout',
  default_value: '28800',
  is_need_restart: '0',
  wait_timeout: 'erehak',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_time',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_timeout',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_timeout',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_timeout',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_timeout',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}, {
  option: 'wait_timeout',
  wait_timeout: 'erehak',
  is_need_restart: '0',
  default_value: '28800',
  scope: '[1-300]',
  desc: '交互连接超时时长'
}]
export const mysqlIdList = [{
  value: 'mysql-pfllk1',
  label: 'mysql-pfllk1'
}, {
  value: 'mysql-pfllk2',
  label: 'mysql-pfllk2'
}, {
  value: 'mysql-pfllk3',
  label: 'mysql-pfllk3'
}]
