export const overview_list = [{
  connection_string: ["mysql -h123.33.2.4 -P1216 -u11 -p ", "jdbc:mysql://123.33.2.4:1216"],
  create_time: "2018-06-28 16:22:03",
  db_service_name: "cececee",
  extended_enable: false,
  ip: "123.33.2.4",
  is_ha_enable: true,
  is_mgr_enable: false,
  is_ra_enable: false,
  is_rws_enable: false,
  master_mysql_id: "mysql-baxxe5",
  max_connection: "1000",
  mysql_admin_password: "",
  mysql_group_id: "mysql-group-yumgm3",
  mysql_instances: [{
    mysql_id: "mysql-baxxe5",
    is_master: true,
    is_write: false,
    cpu: "",
    memory: "",
    disk: "",
    ip: "172.16.122.1",
    port: "4752",
    role: "STATUS_MYSQL_MASTER",
    sip: "(SIP)",
    status: "STATUS_MYSQL_HEALTH_OK"
  },
    {
      mysql_id: "mysql-wh46q4",
      is_master: true,
      is_write: false,
      cpu: "",
      memory: "",
      disk: "",
      ip: "172.16.122.2",
      port: "4752",
      role: "STATUS_MYSQL_MASTER",
      sip: "(SIP)",
      status: "STATUS_MYSQL_HEALTH_OK"
    }],
  mysql_password: "",
  mysql_user: "11",
  mysql_version: "5.7",
  notify_display_names: ["root"],
  notify_users: ["root/root"],
  own_group: "root",
  own_user: "root",
  own_user_name: "root",
  port: "4752",
  price: "12.00",
  ra_zone_id: "23",
  ra_zone_name: "dee",
  remark: "qww",
  run_status: "STATUS_MYSQL_HEALTH_OK",
  service_class: {service_class_id: "class-min", service_class_name: "小型", day_price: 0, cpu: 1, memory: 256, disk: 10},
  service_id: "service-gwwfns",
  temp_instances: null,
  zone_id: "zone-sample",
  zone_name: "示例"
}]

